Fix WriteBuffer import - use foundation instead of typed_data
- Changed from dart:typed_data to package:flutter/foundation.dart
- WriteBuffer is defined in Flutter foundation library
- Fixes compilation error: 'WriteBuffer isn't a type'